// Code generated by scripts/gen-tables.py from crates/oride-keymap/src/action.rs. DO NOT EDIT.

// Package action is the canonical table of editor actions.
//
// An action is a stable string id, not an enum: in the Rust implementation a
// variant and a TOML id were two identities joined by a parser that could
// disagree with itself. Here the string is the identity, so a config keymap, a
// palette entry and a keybinding all name the same thing by construction.
package action

// Action is a stable action id. The zero value is not a valid action.
type Action string

// Action ids, in the declaration order of the Rust canonical table.
const (
	Quit                  Action = "quit"
	Save                  Action = "save"
	SaveAs                Action = "save_as"
	SaveAll               Action = "save_all"
	Undo                  Action = "undo"
	Redo                  Action = "redo"
	InsertNewline         Action = "insert_newline"
	InsertTab             Action = "insert_tab"
	Backspace             Action = "backspace"
	Delete                Action = "delete"
	MoveLeftPlain         Action = "move_left"
	MoveRightPlain        Action = "move_right"
	MoveUpPlain           Action = "move_up"
	MoveDownPlain         Action = "move_down"
	MoveLineStartPlain    Action = "move_line_start"
	MoveLineEndPlain      Action = "move_line_end"
	MoveDocStartPlain     Action = "move_doc_start"
	MoveDocEndPlain       Action = "move_doc_end"
	MoveLeftExtend        Action = "move_left_extend"
	MoveRightExtend       Action = "move_right_extend"
	MoveUpExtend          Action = "move_up_extend"
	MoveDownExtend        Action = "move_down_extend"
	MoveLineStartExtend   Action = "move_line_start_extend"
	MoveLineEndExtend     Action = "move_line_end_extend"
	MoveDocStartExtend    Action = "move_doc_start_extend"
	MoveDocEndExtend      Action = "move_doc_end_extend"
	SelectAll             Action = "select_all"
	PageUp                Action = "page_up"
	PageDown              Action = "page_down"
	ToggleTree            Action = "toggle_tree"
	ToggleTerminal        Action = "toggle_terminal"
	TerminalGrow          Action = "terminal_grow"
	TerminalShrink        Action = "terminal_shrink"
	TreeGrow              Action = "tree_grow"
	TreeShrink            Action = "tree_shrink"
	FocusTree             Action = "focus_tree"
	FocusEditor           Action = "focus_editor"
	FocusTerminal         Action = "focus_terminal"
	NextTab               Action = "next_tab"
	PrevTab               Action = "prev_tab"
	CloseTab              Action = "close_tab"
	NewTab                Action = "new_tab"
	CommandPalette        Action = "command_palette"
	OpenFileFuzzy         Action = "open_file_fuzzy"
	TreeNewFile           Action = "tree_new_file"
	TreeNewDir            Action = "tree_new_dir"
	TreeRefresh           Action = "tree_refresh"
	OpenFolder            Action = "open_folder"
	FocusToggleTreeEditor Action = "focus_toggle_tree_editor"
	ToggleSoftWrap        Action = "toggle_soft_wrap"
	ToggleComment         Action = "toggle_comment"
	ToggleMdPreview       Action = "toggle_md_preview"
	Help                  Action = "help"
	Find                  Action = "find"
	FindNext              Action = "find_next"
	FindPrev              Action = "find_prev"
	ProjectFind           Action = "project_find"
	ProjectReplace        Action = "project_replace"
	Replace               Action = "replace"
	Copy                  Action = "copy"
	Paste                 Action = "paste"
	Cut                   Action = "cut"
	ReloadFile            Action = "reload_file"
	LspComplete           Action = "lsp_complete"
	LspHover              Action = "lsp_hover"
	LspGotoDefinition     Action = "lsp_goto_definition"
	LspFormat             Action = "lsp_format"
	ToggleDiagnostics     Action = "toggle_diagnostics"
	SplitVertical         Action = "split_vertical"
	SplitHorizontal       Action = "split_horizontal"
	FocusNextPane         Action = "focus_next_pane"
	ClosePane             Action = "close_pane"
	ResizePaneGrow        Action = "resize_pane_grow"
	ResizePaneShrink      Action = "resize_pane_shrink"
	AddCursorAbove        Action = "add_cursor_above"
	AddCursorBelow        Action = "add_cursor_below"
	ClearExtraCursors     Action = "clear_extra_cursors"
	ToggleScm             Action = "toggle_scm"
	FocusScm              Action = "focus_scm"
	GitPull               Action = "git_pull"
	GitPush               Action = "git_push"
	BufferPicker          Action = "buffer_picker"
	JumpBack              Action = "jump_back"
	JumpForward           Action = "jump_forward"
	WhichKey              Action = "which_key"
	Welcome               Action = "welcome"
	ShowDiff              Action = "show_diff"
	Surround              Action = "surround"
	MultiPicker           Action = "multi_picker"
	UndoTree              Action = "undo_tree"
	ToggleMouse           Action = "toggle_mouse"
	SelectTheme           Action = "select_theme"
	SelectLocale          Action = "select_locale"
	HealthCheck           Action = "health_check"
	ToggleModal           Action = "toggle_modal"
	RunTasks              Action = "run_tasks"
)

// all is the canonical table, in declaration order.
var all = []Action{
	Quit,
	Save,
	SaveAs,
	SaveAll,
	Undo,
	Redo,
	InsertNewline,
	InsertTab,
	Backspace,
	Delete,
	MoveLeftPlain,
	MoveRightPlain,
	MoveUpPlain,
	MoveDownPlain,
	MoveLineStartPlain,
	MoveLineEndPlain,
	MoveDocStartPlain,
	MoveDocEndPlain,
	MoveLeftExtend,
	MoveRightExtend,
	MoveUpExtend,
	MoveDownExtend,
	MoveLineStartExtend,
	MoveLineEndExtend,
	MoveDocStartExtend,
	MoveDocEndExtend,
	SelectAll,
	PageUp,
	PageDown,
	ToggleTree,
	ToggleTerminal,
	TerminalGrow,
	TerminalShrink,
	TreeGrow,
	TreeShrink,
	FocusTree,
	FocusEditor,
	FocusTerminal,
	NextTab,
	PrevTab,
	CloseTab,
	NewTab,
	CommandPalette,
	OpenFileFuzzy,
	TreeNewFile,
	TreeNewDir,
	TreeRefresh,
	OpenFolder,
	FocusToggleTreeEditor,
	ToggleSoftWrap,
	ToggleComment,
	ToggleMdPreview,
	Help,
	Find,
	FindNext,
	FindPrev,
	ProjectFind,
	ProjectReplace,
	Replace,
	Copy,
	Paste,
	Cut,
	ReloadFile,
	LspComplete,
	LspHover,
	LspGotoDefinition,
	LspFormat,
	ToggleDiagnostics,
	SplitVertical,
	SplitHorizontal,
	FocusNextPane,
	ClosePane,
	ResizePaneGrow,
	ResizePaneShrink,
	AddCursorAbove,
	AddCursorBelow,
	ClearExtraCursors,
	ToggleScm,
	FocusScm,
	GitPull,
	GitPush,
	BufferPicker,
	JumpBack,
	JumpForward,
	WhichKey,
	Welcome,
	ShowDiff,
	Surround,
	MultiPicker,
	UndoTree,
	ToggleMouse,
	SelectTheme,
	SelectLocale,
	HealthCheck,
	ToggleModal,
	RunTasks,
}

// paletteOrder is the curated order of the command palette.
var paletteOrder = []Action{
	Save,
	SaveAs,
	SaveAll,
	Undo,
	Redo,
	Find,
	FindNext,
	FindPrev,
	ProjectFind,
	ProjectReplace,
	Replace,
	SelectAll,
	Copy,
	Paste,
	Cut,
	ToggleComment,
	ToggleSoftWrap,
	ToggleMdPreview,
	NewTab,
	CloseTab,
	NextTab,
	PrevTab,
	OpenFolder,
	OpenFileFuzzy,
	CommandPalette,
	Help,
	ToggleTree,
	ToggleTerminal,
	TerminalGrow,
	TerminalShrink,
	TreeGrow,
	TreeShrink,
	FocusTree,
	FocusEditor,
	FocusToggleTreeEditor,
	FocusTerminal,
	TreeNewFile,
	TreeNewDir,
	TreeRefresh,
	ReloadFile,
	LspComplete,
	LspHover,
	LspGotoDefinition,
	LspFormat,
	ToggleDiagnostics,
	SplitVertical,
	SplitHorizontal,
	FocusNextPane,
	ClosePane,
	ResizePaneGrow,
	ResizePaneShrink,
	AddCursorAbove,
	AddCursorBelow,
	ClearExtraCursors,
	ToggleScm,
	FocusScm,
	GitPull,
	GitPush,
	BufferPicker,
	JumpBack,
	JumpForward,
	WhichKey,
	Welcome,
	ShowDiff,
	Surround,
	MultiPicker,
	UndoTree,
	ToggleMouse,
	SelectTheme,
	SelectLocale,
	HealthCheck,
	ToggleModal,
	RunTasks,
	Quit,
}
